In [11]:
import numpy as np

nbits = 4 #number of hyperplanes and binary vals to produce
d     = 2 #vector dimensions

In [12]:
#create a set of 4 hyperplanes, with 2 dimensions
plane_norms = np.random.rand(nbits, d) - .5
plane_norms

array([[-0.42887053,  0.2169168 ],
       [ 0.24903873,  0.42847606],
       [ 0.2813722 , -0.26780729],
       [ 0.02451008,  0.16421681]])

In [13]:
#hash vectors

a = np.asarray([1, 2])
b = np.asarray([2, 1])
c = np.asarray([3, 1])


In [14]:
#caculate the dot product for each of thess
a_dot = np.dot(a, plane_norms.T)
b_dot = np.dot(b, plane_norms.T)
c_dot = np.dot(c, plane_norms.T)

a_dot, b_dot, c_dot

(array([ 0.00496307,  1.10599086, -0.25424238,  0.35294371]),
 array([-0.64082426,  0.92655353,  0.29493712,  0.21323697]),
 array([-1.06969478,  1.17559226,  0.57630932,  0.23774704]))

In [15]:
# we know that a positive dot product == +ve side of hyperplane
# and negative dot product == -ve side of hyperplane

a_dot = a_dot > 0
b_dot = b_dot > 0
c_dot = c_dot > 0

a_dot

array([ True,  True, False,  True])

In [16]:
# convert our boolen arrays to int arrays to make bucketing
# easier (although is okay to use boolen for hamming distance)

a_dot = a_dot.astype(int)
b_dot = b_dot.astype(int)
c_dot = c_dot.astype(int)

a_dot

array([1, 1, 0, 1])

In [17]:
b_dot, c_dot

(array([0, 1, 1, 1]), array([0, 1, 1, 1]))

In [18]:
vectors = [a_dot, b_dot, c_dot]
buckets = {}
i = 0

for i in range(len(vectors)):
    #convert from array to sring
    hash_str = ''.join(vectors[i].astype(str))
    
    #create bucket if it doesn't exist
    if hash_str not in buckets.keys():
        buckets[hash_str] = []
        
    buckets[hash_str].append(i)

buckets

{'1101': [0], '0111': [1, 2]}

In [19]:

nbits = 4

# we can print every possible bucket given our nbits value like so
for i in range(1 << nbits):
    #get binary representation of integer
    b = bin(i)[2:]
    # pad zeros to start of binary represention
    b = '0' * (nbits- len(b)) + b
    print(b, end=' | ')

0000 | 0001 | 0010 | 0011 | 0100 | 0101 | 0110 | 0111 | 1000 | 1001 | 1010 | 1011 | 1100 | 1101 | 1110 | 1111 | 

In [20]:
for nbits in [2, 4, 8, 16]:
    print(f"nbits: {nbits}, buckets: {1 << nbits}")

nbits: 2, buckets: 4
nbits: 4, buckets: 16
nbits: 8, buckets: 256
nbits: 16, buckets: 65536


##FAISS

In [ ]:
import faiss

d = wb.shape[1]
nbits = 4

# initialize the index using our vectors dimesionality (128) and nbits
index = faiss.IndexLSH(d, nbits)

#then add the data
index.add(wb)